allowBuilds:
  bufferutil: true
  electron-winstaller: true
  es5-ext: true
  esbuild: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - svelte@5.56.7
  - daisyui@5.7.0
  - vite-plugin-sveltekit-ws@1.0.0
onlyBuiltDependencies:
  - "@prisma/client"
  - better-sqlite3
  - esbuild
